### PR TITLE
#37 - add custom rendering for exceptions

### LINKED ISSUE #37: Add custom rendering for exceptions
Create custom views and use them to render exceptions

### PR DESCRIPTION
**Pull request by PrabuckiDominik**
This should close #37

### CODE REVIEW

File: bootstrap/app.php [hunk 1]
```diff
@@ -16,4 +19,17 @@
     ->withMiddleware(function (Middleware $middleware): void {
     })
     ->withExceptions(function (Exceptions $exceptions): void {
+        $exceptions->respond(function (Response $response, Throwable $exception, Request $request) {
```
Comment (kamilpiech97) [inline bootstrap/app.php]: Return type

File: bootstrap/app.php [hunk 2]
```diff
@@ -16,4 +19,17 @@
...
+            if (!app()->environment(["local", "testing"]) && in_array($response->getStatusCode(), [500, 503, 404, 403], true)) {
```
Comment (kamilpiech97) [inline bootstrap/app.php]: Should not be better to get http status codes from `SymfonyResponse`?

File: bootstrap/app.php [hunk 3]
```diff
@@ -16,4 +21,17 @@
     ->withMiddleware(function (Middleware $middleware): void {
     })
     ->withExceptions(function (Exceptions $exceptions): void {
+        $exceptions->respond(function (Response $response, Throwable $exception, Request $request): Response {
+            if (!app()->environment(["local", "testing"]) && in_array($response->getStatusCode(), [Response::HTTP_FORBIDDEN, Response::HTTP_INTERNAL_SERVER_ERROR, Response::HTTP_SERVICE_UNAVAILABLE, Response::HTTP_NOT_FOUND], true)) {
```
Comment (kamilpiech97) [inline bootstrap/app.php]: Lets move that codes into array, similiar as a code added above.

File: bootstrap/app.php [hunk 4]
```diff
@@ -5,6 +5,17 @@
 use Illuminate\Foundation\Application;
 use Illuminate\Foundation\Configuration\Exceptions;
 use Illuminate\Foundation\Configuration\Middleware;
+use Illuminate\Http\Request;
+use Inertia\Inertia;
+use Symfony\Component\HttpFoundation\Response;
+
+const HTTP_SESSION_EXPIRED = 419;
+const HANDLED_ERROR_CODES = [
```
Comment (kamilpiech97) [inline bootstrap/app.php:13]:
```suggestion
protected const array HTTP_SESSION_EXPIRED = 419;
protected const array HANDLED_ERROR_CODES = [
```

**Review by kamilpiech97 — APPROVED** [review]
